#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="app/$APP"

echo '--- ZeroMQ: Download ---';
id=$(docker run -i -a stdin $IMAGE /bin/bash -c "apt-get update -y && apt-get install -y libtool autoconf automake make g++ uuid-dev wget && wget http://download.zeromq.org/zeromq-3.2.4.tar.gz && tar -zxvf zeromq-3.2.4.tar.gz && cd zeromq-3.2.4 && ./configure && make && make install");
docker attach $id
test $(docker wait $id) -eq 0;
docker commit $id $IMAGE > /dev/null
 
# Install zmq library
#-------------------
#export LD_LIBRARY_PATH=~/local/lib/
#export PKG_CONFIG_PATH=~/local/lib/pkgconfig/
 
# in some OS's you may need this too:
#export CXXFLAGS="-I ~/local/include"
#export LDFLAGS="-L ~/local/lib/ -Wl,-rpath=~/local/lib/"
